### ISSUE TITLE
Link to Campings

### ISSUE THREAD

**Issue by bdombar** [Holinvan/holinvan-web#1]
@Holinvan/team-b 
Hay que arreglar el link a Campings desde la sesión iniciada de usuario

**Comment by vscarmena** [comment]
@bdombar @Holinvan/team-b Modifico el hello.html y navbar.html para meterlo dentro de una plantilla y no tener código duplicado. Gracias @bdombar

**Comment by BigThor23** [comment]
Corregido el link a campinglist en la navbar, ahora redirige bien.
