### ISSUE TITLE
Bad redirections detected

### ISSUE THREAD

**Issue by cediar** [Holinvan/holinvan-web#13]
Este post de issues es para ir recopilando redirecciones erróneas o links defectuosos.

- Al clickar en el logo de Holinvan (banner), éste redirige a: http://www.holinvan.com/holinvan-web, mostrando un 404.

**Comment by cediar** [comment]
@vscarmena hay que corregir la URL en el proyecto migrado!!!

**Comment by vscarmena** [comment]
Done @cediar
