### ISSUE TITLE
Mensajes&ValidaciónEnGestiónCaravana

### ISSUE THREAD

**Issue by MarcosYeste** [Holinvan/holinvan-web#16]
### Mensajes:
   -El texto de  **"Tienes seguro?"** aparece dos veces.

### Validaciones : 
   -**En Alemán** la validacion en el año de construcción cuando dejas el campo en blanco se muestra
     un "introduzca" .
  -**En Italiano** las validaciones de la ultima pagina cuando dejas el campo en blanco se muestran en 
      inglés.

**Comment by amaloro100** [comment]
Hay un comentario al respecto en el issue de mensajes e internacionalización, por eso no se ha cerrado.
