### ISSUE TITLE
Issues at Caravan Registration

### ISSUE THREAD

**Issue by cediar** [Holinvan/holinvan-web#3]
- A la hora de registrar la caravana, en la 3ª parte del formulario donde se recogen las características de la misma, los textos de la mitad de los checkboxes necesitan traducción.
- Al guardar, peta porque en el CaravanController, línea 46, está mal direccionada la html.
- Si se corrigiese el punto anterior, el controlador redirige a una página en blanco con un texto genérico: debería redirigir a la página de inicio, JUNTO CON UN MENSAJE DE CONFIRMACIÓN.
@Holinvan/team-a 

- FALTA NAVBAR!!!

Por lo demás, todo bien.

**Comment by amaloro100** [comment]
Arreglado
