### ISSUE TITLE
Traducciones de gestion caravana html

### ISSUE THREAD

**Issue by Jesu3** [Holinvan/holinvan-web#6]
Falta traducir los siguientes pasos del html GestionCaravanas

![select traduccion](https://cloud.githubusercontent.com/assets/25979394/24608882/bca7172e-1878-11e7-997d-4e9882693183.PNG)
![traduccion booking](https://cloud.githubusercontent.com/assets/25979394/24608881/bca6e1f0-1878-11e7-8485-86e71a220fab.PNG)
![traduccion availability](https://cloud.githubusercontent.com/assets/25979394/24608883/bca7f87e-1878-11e7-8f91-cc5f1b6fbd4a.PNG)

**Comment by JordiCT** [comment]
Ya está toda la página de registro de caravanas internacionalizada
