### ISSUE TITLE
Arreglar paraula "smoke/smokers" en messages.properties

### ISSUE THREAD

**Issue by Alroja** [Holinvan/holinvan-web#8]

**Comment by Alroja** [comment]
Apart estic amb lo que es té que traduir del 6.4 i 6.5 que m'ha passat el Jordi.

**Comment by Alroja** [comment]
Text del Jordi corretgits:

success.html

	TU CARAVANA SE HA AÑADIDO CORRECTAMENTE fet

	TITLE fet

	BOTÓN fet



price.html

	TITLE fet

	initDate fet

	endDate fet

	price fet

	BOTÓN ja está fet

	FECHA DE INICIO fet

	FECHA DE FIN fet

	PRECIO fet


calendar.html

	TITLE fet

	initDate fet

	endDate fet

	BOTÓN ja está fet

	FECHA DE INICIO fet

	FECHA DE FIN fet

"Smoke" es la paraula que es fa servir en gestioncaravana.html, no smokers.

**Comment by JordiCT** [comment]
Solucionat
